/* ================================================================
 Marinor NTNU – text updates (used by the page components)
 ================================================================ */

/* ---------- Text updates ----------
 Some pages still have older wording saved on the Framer canvas (also per breakpoint).
 Any old sentence found in a text prop is swapped for the current one, so the site
 shows the new text everywhere. Old → new, longest first. */
const COPY_UPDATES: [string, string][] = [
    ["Two lenses give Argus depth vision, so it can see and measure what is in front of it.", "Two lenses measure the distance to things in front of the boat. The images are also used to recognise what the objects are."],
    ["Our first autonomous boat. A catamaran with LiDAR, a stereo camera and two GNSS antennas.", "Our first autonomous boat. A catamaran with LiDAR, a stereo depth camera and a Kongsberg Seapath 130."],
    ["Catamaran · 3D LiDAR · Stereo camera · Dual GNSS", "Catamaran · LiDAR · Stereo camera · Seapath 130"],
    ["Njord – The Autonomous Ship Challenge is run by Njord NTNU, a student organisation started in Trondheim in 2019. Every year they invite student teams from around the world to Nyhavna in Trondheim.\nEach team designs, builds and operates its own autonomous surface vessel. During the week the boats have to solve tasks on the water with no one steering them. In 2025 eleven teams from eight countries took part, and Navier USN from Norway won.\nThe point is not only to win. Teams get to test theory in practice, work across many fields and meet others who build the same kind of technology.", "Njord: The Autonomous Ship Challenge is run by Njord NTNU, a student organisation started in Trondheim in 2019. Every August student teams come to Nyhavna in Trondheim.\nEach team builds and runs its own autonomous boat. During the week the boats solve tasks on the water with no one steering. In 2025 eleven teams from eight countries took part, and Navier USN from Norway won."],
    ["Njord: The Autonomous Ship Challenge is run by Njord NTNU, a student organisation started in Trondheim in 2019. Every year they invite student teams from around the world to Nyhavna in Trondheim.\nEach team designs, builds and operates its own autonomous surface vessel. During the week the boats have to solve tasks on the water with no one steering them. In 2025 eleven teams from eight countries took part, and Navier USN from Norway won.\nTeams also use the week to test their ideas on real water and meet others who build the same kind of boats.", "Njord: The Autonomous Ship Challenge is run by Njord NTNU, a student organisation started in Trondheim in 2019. Every August student teams come to Nyhavna in Trondheim.\nEach team builds and runs its own autonomous boat. During the week the boats solve tasks on the water with no one steering. In 2025 eleven teams from eight countries took part, and Navier USN from Norway won."],
    ["Marinor NTNU is a technical student organisation at the Norwegian University of Science and Technology. We develop autonomous maritime vessels – boats that can find their own way on the water.\nWe bring together students with strong skills in robotics, automation and marine technology. Together with the Department of Engineering Cybernetics, we build knowledge and new products in maritime autonomy.\nThe organisation was founded in 2025. It already has more than 35 members, and it keeps growing fast.", "Marinor NTNU is a technical student organisation at NTNU. We build autonomous boats that find their way on the water without anyone steering.\nOur members study robotics, automation, marine technology and other subjects. We work with the Department of Engineering Cybernetics.\nMarinor was founded in 2025 and has more than 35 members."],
    ["Marinor NTNU is a technical student organisation at the Norwegian University of Science and Technology. We develop autonomous boats that can find their own way on the water.\nWe bring together students with strong skills in robotics, automation and marine technology. Together with the Department of Engineering Cybernetics, we build knowledge and new products in maritime autonomy.\nThe organisation was founded in 2025. It already has more than 35 members, and it keeps growing fast.", "Marinor NTNU is a technical student organisation at NTNU. We build autonomous boats that find their way on the water without anyone steering.\nOur members study robotics, automation, marine technology and other subjects. We work with the Department of Engineering Cybernetics.\nMarinor was founded in 2025 and has more than 35 members."],
    ["Argus is our first autonomous surface vessel – a boat that can find its way on the water with no one at the wheel.\nIt is also where everything we learn comes together. Hulls, electronics, sensors, control systems and software all have to work as one. Every part is designed, built and tested by students, which gives our members real hands-on experience in maritime autonomy.", "Argus is our first autonomous surface vessel. It finds its way on the water with no one at the wheel.\nThe hulls, electronics, sensors, control system and software all have to work together on one boat. Our members made every part of it."],
    ["Argus is our first autonomous surface vessel. It finds its way on the water with no one at the wheel.\nHulls, electronics, sensors, control systems and software all have to work together on one boat. Every part is designed, built and tested by students, which gives our members real hands-on experience in maritime autonomy.", "Argus is our first autonomous surface vessel. It finds its way on the water with no one at the wheel.\nThe hulls, electronics, sensors, control system and software all have to work together on one boat. Our members made every part of it."],
    ["Based in Trondheim, we bring together students with strong backgrounds in robotics, automation and marine technology to drive innovation in autonomous maritime vessels. Together with the Department of Engineering Cybernetics, we turn theory into boats that work on real water.", "Our members study robotics, automation, marine technology and other subjects at NTNU. We work with the Department of Engineering Cybernetics, and we build, program and test the boats ourselves in Trondheim."],
    ["Marinor NTNU is on the team list for the Njord Challenge 2026. Argus, our first autonomous boat, is built for exactly these tasks: find the way, see what is around it, avoid other boats and dock on its own.", "Marinor NTNU is on the team list for the Njord Challenge 2026. We built Argus for these four tasks: find the way, see what is around it, avoid other boats and dock."],
    ["An international student competition for autonomous boats, held every summer in Trondheim. Teams from all over the world bring the boats they have built and let them sail on their own.", "A student competition for autonomous boats, held every August in Trondheim. Teams from several countries bring boats they have built and let them sail on their own."],
    ["In 2028 we plan to start building a much bigger boat. It is the first real step towards our dream: a boat that sails on its own along the whole Norwegian coast – with a crew on board.", "In 2028 we plan to start building a much bigger boat. The long-term goal is a boat that can sail the Norwegian coast on its own with a crew on board."],
    ["In 2028 we plan to start building a much bigger boat. It is the first real step towards our dream: a boat that sails on its own along the whole Norwegian coast with a crew on board.", "In 2028 we plan to start building a much bigger boat. The long-term goal is a boat that can sail the Norwegian coast on its own with a crew on board."],
    ["We are a student organisation at NTNU developing autonomous maritime solutions – boats that find their own way on the water. Designed, built and tested by students in Trondheim.", "We are a student organisation at NTNU that builds autonomous boats. Our first boat, Argus, sailed in the Njord Challenge in Trondheim in 2026."],
    ["We took part in Njord – The Autonomous Ship Challenge, and held our own against prestigious universities from all over the world. A huge step for a team in its first full year.", "We sail Argus in Njord: The Autonomous Ship Challenge in Trondheim, against university teams from several countries."],
    ["We are constantly looking for new sponsors and collaborators. If you are interested in becoming our next one, get in touch with our Head of Sponsorship and Branding.", "We are looking for new sponsors and partners. If your company wants to support us, contact our Head of Sponsorship and Branding."],
    ["In 2027 our goal is simple: win the Njord Challenge. After that, we want to compete in RoboBoat – one of the biggest competitions for autonomous boats in the world.", "In 2027 we want to win the Njord Challenge. After that we want to enter RoboBoat in Florida."],
    ["Our long-term goal is to scale up the boat we build for competitions. One day it should sail autonomously along the whole Norwegian coast – with a crew on board.", "In the long run we want to scale up our competition boat. The goal is a boat that sails the whole Norwegian coast on its own, with people on board."],
    ["Our long-term goal is to scale up the boat we build for competitions. One day it should sail autonomously along the whole Norwegian coast with a crew on board.", "In the long run we want to scale up our competition boat. The goal is a boat that sails the whole Norwegian coast on its own, with people on board."],
    ["In 2027 our goal is simple: win the Njord Challenge. After that we want to enter RoboBoat in Florida, one of the biggest competitions for autonomous boats.", "In 2027 we want to win the Njord Challenge. After that we want to enter RoboBoat in Florida."],
    ["Marinor NTNU is founded in Trondheim. The first members get to work in the workshop, and our first autonomous boat, Argus, slowly starts to take shape.", "Four students start Marinor NTNU in Trondheim. The first members build the hulls for Argus in the workshop."],
    ["We are a student organisation at NTNU in Trondheim. We design, build and test autonomous boats – and take them to competitions around the world.", "Marinor NTNU is a student organisation at NTNU in Trondheim. We build autonomous boats and enter them in student competitions."],
    ["Autonomous boats are built to be tested. Read about Njord, the challenge we sail in Trondheim, or RoboBoat in Florida, where we want to go next.", "Read about Njord in Trondheim, where we sail Argus, or RoboBoat in Florida, where we want to go next."],
    ["The boats sail a course in the harbour and are given one task at a time. Everything has to happen on its own – the team is not allowed to steer.", "The boats sail a course in the harbour and get one task at a time. The team is not allowed to steer."],
    ["Two boats, one goal: autonomy at sea. Read about Argus, the boat we built and took out on the water – or see what we are working on next.", "Read about Argus, the boat we have built and tested, or Proteus, the boat we are designing now."],
    ["We wish to collaborate with companies interested in technology development and innovation, and who want to help us realize our ambitions.", "We want to work with companies that care about new technology and want to help students build it."],
    ["Two boats, one goal: autonomy at sea. Read about Argus, the boat we built and took out on the water, or see what we are working on next.", "Read about Argus, the boat we have built and tested, or Proteus, the boat we are designing now."],
    ["We take in new members once in a while, not all year. Follow us on Instagram – we post there as soon as we open for applications again.", "We take in new members at set times. Follow us on Instagram, where we post when applications open."],
    ["A student organisation at NTNU that designs, builds and tests autonomous boats – from the workshop in Trondheim to competitions abroad.", "A student organisation at NTNU in Trondheim that builds autonomous boats."],
    ["All the rules, dates and team lists live on RoboBoat's own website. You can also read about the competition we take part in ourselves.", "The rules, dates and team lists are on RoboBoat's website. You can also read about Njord, the competition we sail in."],
    ["Autonomous boats are built to be tested. In 2026 we took Argus to the Njord Challenge – next, we are aiming for RoboBoat in Florida.", "We took Argus to the Njord Challenge in Trondheim in 2026. Next we want to go to RoboBoat in Florida."],
    ["We are a student organisation at NTNU in Trondheim. We design, build and test autonomous boats and take them to competitions abroad.", "Marinor NTNU is a student organisation at NTNU in Trondheim. We build autonomous boats and enter them in student competitions."],
    ["Write to us and you will get an honest answer about the groups, how much time it takes and what a year at Marinor really looks like.", "Write to us and ask about the groups, how much time it takes or anything else."],
    ["Autonomous boats are built to be tested. In 2026 we took Argus to the Njord Challenge. Next we are aiming for RoboBoat in Florida.", "We took Argus to the Njord Challenge in Trondheim in 2026. Next we want to go to RoboBoat in Florida."],
    ["We build autonomous boats in Trondheim. Open to all NTNU students – you do not need to know anything about boats before you start.", "We build autonomous boats in Trondheim. All NTNU students can apply, and you do not need to know anything about boats."],
    ["We build autonomous boats in Trondheim. Open to all NTNU students. You do not need to know anything about boats before you start.", "We build autonomous boats in Trondheim. All NTNU students can apply, and you do not need to know anything about boats."],
    ["Send us an email and we will get back to you. We are happy to tell you more about Marinor and what a partnership could look like.", "Send us an email and we will answer. We can tell you more about Marinor and what a partnership could look like."],
    ["Thank you to the companies and organizations that back Marinor NTNU and help us take our vessels from the workshop to the water.", "These companies and organisations support Marinor NTNU. Without them we could not build our boats or travel to competitions."],
    ["The Autonomous Ship Challenge in Trondheim, where student teams from around the world let their boats solve tasks on their own.", "A student competition in Trondheim where autonomous boats solve tasks in the harbour without anyone steering."],
    ["We take in new members once in a while, not all year. Follow us on Instagram. We post there as soon as applications open again.", "We take in new members at set times. Follow us on Instagram, where we post when applications open."],
    ["We took part in Njord: The Autonomous Ship Challenge in our first full year, against university teams from all over the world.", "We sail Argus in Njord: The Autonomous Ship Challenge in Trondheim, against university teams from several countries."],
    ["We are always looking for curious students – in software, electronics, mechanics, design and more. No boat experience needed.", "We need students in software, electronics, mechanics, design and more. You do not need any boat experience."],
    ["The tasks copy real problems from the maritime industry, like watching the coast, keeping a port safe and other work at sea.", "The tasks are based on work boats do at sea, like watching a coastline or keeping a port safe."],
    ["A student organisation at NTNU that designs, builds and tests autonomous boats in Trondheim and takes them to competitions.", "A student organisation at NTNU in Trondheim that builds autonomous boats."],
    ["The Autonomous Ship Challenge in Trondheim. Student teams from around the world let their boats solve tasks on their own.", "A student competition in Trondheim where autonomous boats solve tasks in the harbour without anyone steering."],
    ["We are a student organisation at NTNU that builds autonomous boats. Designed, built and tested by students in Trondheim.", "We are a student organisation at NTNU that builds autonomous boats. Our first boat, Argus, sailed in the Njord Challenge in Trondheim in 2026."],
    ["Our first autonomous boat. Designed, built and tested by students in Trondheim – from the first sketch to open water.", "Our first autonomous boat. A catamaran built by students in Trondheim and tested in the harbour."],
    ["Proteus is our next step in maritime autonomy. We are still working on this page — come back soon for the full story.", "Proteus is our next boat. This page is not ready yet."],
    ["The rules, the schedule and the team list all live on Njord's own website. You can also read how we built our boat.", "The rules, the schedule and the team list are on Njord's website. You can also read how we built our boat."],
    ["The boats sail a course in the harbour and are given one task at a time. The team is not allowed to steer.", "The boats sail a course in the harbour and get one task at a time. The team is not allowed to steer."],
    ["These are the groups we have. Have a look now, so you know what you want to apply for when we open again.", "These are our seven groups. Have a look, so you know which one to apply for."],
    ["The course is built like a small version of real waters, with marks the boat has to read and understand.", "The course has the same kind of marks a boat meets at sea, and the boat has to read them."],
    ["Our GUI team built an interface for following Argus. Take a look, or join us and work on the next boat.", "Our GUI team built a web interface for following Argus while it sails. You can open it here."],
    ["Our GUI team built an interface for Argus. Take a look – or join us and help shape what comes next.", "Our GUI team built a web interface for following Argus while it sails. You can open it here."],
    ["We are always looking for motivated students in robotics, automation, marine technology and beyond.", "We need students in robotics, automation, marine technology and other subjects."],
    ["Everything we build is designed, built and tested by students. This is what your support goes into.", "Materials, electronics, sensors and travel to competitions. Here is some of the work."],
    ["From the first hull in the workshop to launch day in the harbour – this is how Argus came to life.", "The build, from the first hull in the workshop to the first test in the harbour."],
    ["We work closely with the Department of Engineering Cybernetics and with partners in the industry.", "We work with the Department of Engineering Cybernetics and with companies that support us."],
    ["We bring together skilled students and help shape the engineers and industry leaders of tomorrow.", "Members get to know other students, researchers and companies that work with autonomous boats."],
    ["Argus is already out on the water. Proteus, our next step, is taking shape on the drawing board.", "Argus is finished and has been tested in the harbour. Proteus is the next boat, and we are designing it now."],
    ["Our next step in maritime autonomy. We are still working on it – follow along as it takes shape.", "Our next boat. We are working on the design now."],
    ["One of the biggest competitions for autonomous boats in the world, held every year in Florida.", "A large competition for autonomous boats, held every February in Sarasota, Florida."],
    ["Hulls, electronics and software – our members design, build and test every part themselves.", "Members make the hulls, electronics and software themselves and test them in the harbour."],
    ["Our first autonomous surface vessel. Designed, built and tested by students in Trondheim.", "Our first autonomous boat. A catamaran with LiDAR, a stereo depth camera and a Kongsberg Seapath 130."],
    ["Reach engaged future engineers at NTNU and help us build the future of maritime autonomy.", "Support the team and get to know students in robotics, automation and marine technology at NTNU."],
    ["A young organisation with big goals. This is where we have been – and where we are going.", "We started in 2025. Here is what we have done and what we plan next."],
    ["Join the team, or support us as a partner and follow Proteus from the very first sketch.", "Join the team, or support us as a partner while we build Proteus."],
    ["Gain positive brand exposure through Marinor's activities and competition participation.", "Your logo on our website, our boat and our posts from competitions."],
    ["How Argus was built, from the first hull in the workshop to launch day in the harbour.", "The build, from the first hull in the workshop to the first test in the harbour."],
    ["Build and test our first maritime platform that can navigate and do tasks on its own.", "Get Argus to solve all four Njord tasks on its own."],
    ["Work closer with the Department of Engineering Cybernetics and our industry partners.", "Work more with the Department of Engineering Cybernetics and with the companies that support us."],
    ["We meet, talk about goals on both sides and agree on what the partnership looks like.", "We meet and agree on what the partnership should look like."],
    ["We don't just study maritime autonomy. We build it, test it and take it out to sea.", "We build our boats in the workshop and test them in the harbour in Trondheim."],
    ["Our members design, build and test the hulls, electronics and software themselves.", "Members make the hulls, electronics and software themselves and test them in the harbour."],
    ["Lay the foundation for new projects in maritime autonomy, research and innovation.", "Use what we learn from Argus when we build Proteus and the bigger boat."],
    ["See the boat we compete with, or help us get to the next competition as a partner.", "See the boat we compete with, or support us as a partner."],
    ["The students building autonomous vessels at NTNU. Pick a season to meet the crew.", "The students behind Marinor NTNU. Choose a year to see who was on the team."],
    ["Our first autonomous boat. Designed, built and tested by students in Trondheim.", "Our first autonomous boat. A catamaran built by students in Trondheim and tested in the harbour."],
    ["Robotics, automation and marine engineering in the same team, on the same boat.", "Software, electronics and mechanics students work on the same boat."],
    ["Sea marks that tell you which side is safe to pass, just like in real shipping.", "Sea marks that show which side is safe to pass."],
    ["Most points come from what the boat actually does on the water during the week.", "Most points come from what the boat does on the water during the week."],
    ["A closer look at the hardware that lets Argus see, think and move on its own.", "The sensors and hardware Argus uses to see, find its position and steer."],
    ["We are working on this page right now. Come back soon to read the full story.", "This page is not ready yet."],
    ["Points come from more than the sailing. The judges look at the whole project.", "The judges also give points for the report, the video and the presentation."],
    ["Take what we learn at Njord to one of the biggest competitions in the world.", "Enter RoboBoat in Florida with what we learn at Njord."],
    ["Points come from more than the sailing. The jury looks at the whole project.", "The jury also gives points for the report, the presentation and the inspection."],
    ["Help shape and develop Marinor as a student organization from the ground up.", "Marinor started in 2025, so partners have a real say in how we grow."],
    ["Follow the project from the workshop to the water – and to the competitions.", "You follow the project and hear from us during the year and at competitions."],
    ["We started in 2025. Here is what we have done so far and what we plan next.", "We started in 2025. Here is what we have done and what we plan next."],
    ["Budget, sponsors and all the practical work that keeps the project running.", "Budget, sponsors, travel and other practical work."],
    ["Social media, photos, website and how we tell people what we are building.", "Social media, photos and this website."],
    ["Dates, rules, teams and results – everything is on RoboBoat's own website.", "Dates, rules, teams and results are on RoboBoat's own website."],
    ["Follow the project from the workshop to the water and to the competitions.", "You follow the project and hear from us during the year and at competitions."],
    ["Support the development of new technology and student-driven innovation.", "Your support goes into boats that sail without anyone steering."],
    ["Meet the students behind Marinor NTNU's autonomous vessel this season.", "The students who started Marinor NTNU and built Argus."],
    ["Rules, teams, results and news – everything is on Njord's own website.", "Rules, teams, results and news are on Njord's own website."],
    ["The competition is a whole year of work, not only the week in Florida.", "Teams work on their boats for most of the year before the competition week."],
    ["The competition takes a whole year of work before the week in Florida.", "Teams work on their boats for most of the year before the competition week."],
    ["We work with academic departments and partners who follow what we do.", "Our sponsors and partners follow the project and meet the team."],
    ["Hulls, frame, power and electronics. Everything the software runs on.", "Hulls, frame, power and electronics."],
    ["Participate in professionally relevant projects and collaborations.", "Give us problems from your company, or join our tests and projects."],
    ["Dates, rules, teams and results are all on RoboBoat's own website.", "Dates, rules, teams and results are on RoboBoat's own website."],
    ["Work starts in the workshop. The first hull slowly takes shape.", "Work starts in the workshop with the first hull."],
    ["teams signed up for the 2026 challenge – Marinor is one of them", "teams signed up for the 2026 challenge, Marinor among them"],
    ["Rules, teams, results and news are all on Njord's own website.", "Rules, teams, results and news are on Njord's own website."],
    ["Reach engaged and highly qualified future engineers from NTNU.", "Get to know engineering students at NTNU before they graduate."],
    ["robotics automation marine technology autonomous real water.", "robotics automation marine technology ourselves"],
    ["The first float test in the harbour. Does it float? It does.", "The first float test in the harbour. It floats."],
    ["As a partner with Marinor, you will have the opportunity to:", "This is what a partnership gives you."],
    ["Our first autonomous boat is launched in Trondheim harbour.", "Argus goes in the water in Trondheim harbour."],
    ["teams in the 2026 Njord Challenge, and we were one of them", "teams in the 2026 Njord Challenge, Marinor included"],
    ["teams in the 2026 Njord Challenge – we were one of them", "teams in the 2026 Njord Challenge, Marinor included"],
    ["We take Argus to our first international competition.", "We enter the Njord Challenge with Argus."],
    ["Students steering the future of maritime autonomy", "Students who build autonomous boats"],
    ["Four students start building in the workshop.", "Four students start Marinor."],
    ["Want to build the future of the sea with us?", "Want to join?"],
    ["Want to help us build the future of the sea?", "Get in touch."],
    ["technology development innovation ambitions", "technology students"],
    ["You build and test real autonomous boats.", "You work on a boat that goes in the water and enters competitions."],
    ["Our next boat. We are working on it now.", "Our next boat. We are working on the design now."],
    ["Driving ASV innovation from Trondheim.", "Autonomous boats, built by students."],
    ["designed, built and tested by students", "built and tested by students"],
    ["Two boats. One goal: autonomy at sea.", "Our boats."],
    ["From a first idea to the world stage.", "What we have done so far."],
    ["members, and more join every semester", "members in 2026"],
    ["A hub for maritime autonomy at NTNU.", "A student organisation at NTNU."],
    ["Want to be part of the next chapter?", "Want to join the team?"],
    ["The partners who make it possible.", "Thanks to our partners."],
    ["From Trondheim to the world stage.", "Where we compete."],
    ["members – and we keep growing fast", "members in 2026"],
    ["Win Njord. Then take on RoboBoat.", "Win Njord, then RoboBoat"],
    ["Along the entire Norwegian coast.", "Along the Norwegian coast."],
    ["What a year at Marinor gives you.", "What you get out of it."],
    ["From the workshop to open water.", "What your support pays for."],
    ["From the south to the far north", "From Kristiansand to Kirkenes"],
    ["One boat. Every skill we have.", "About Argus"],
    ["Boats that sail by themselves.", "What Njord is."],
    ["Behind every test is a team.", "From the workshop and the harbour."],
    ["Four students, one big idea", "Marinor is founded"],
    ["Hands-on vessel development", "You build real boats"],
    ["Our place in the challenge.", "Marinor at Njord."],
    ["Small boats, real problems.", "What RoboBoat is."],
    ["Shape us from the ground up", "Help us early"],
    ["Two ways to come aboard.", "Join us or support us."],
    ["Holding our own at Njord", "First Njord Challenge"],
    ["Real boats. Real skills.", "What we do."],
    ["Straight from the source", "Links"],
    ["students started it all", "students started Marinor"],
    ["What we want to achieve", "Our goals"],
    ["Follow Argus from shore", "Open the Argus interface"],
    ["From workshop to water.", "A year of work, then a week in Florida."],
    ["Why we follow this one.", "Why RoboBoat."],
    ["Positive brand exposure", "Visibility"],
    ["We learn from the best", "We work with NTNU"],
    ["From workshop to water", "How we built it"],
    ["Building the big boat", "A bigger boat"],
    ["Explore the interface", "Open the interface"],
    ["What makes Argus work", "What is on board"],
    ["Stronger partnerships", "More partners"],
    ["A base for the future", "Next projects"],
    ["Work on real projects", "Work with us"],
    ["Where you could fit.", "Our groups."],
    ["Four tasks to solve.", "The four tasks."],
    ["Back new technology", "Support new technology"],
    ["Work across fields", "You work across subjects"],
    ["We build for real", "We build"],
    ["We grow a network", "We meet people"],
    ["Meet the industry", "You meet companies"],
    ["Life on the dock", "Photos from the dock"],
    ["Join the crew.", "Join the team."],
    ["Our journey", "Timeline"]
]
export function freshCopy<T>(props: T): T {
    if (!props || typeof props !== "object") return props
    let changed = false
    const out: any = { ...(props as any) }
    for (const key of Object.keys(out)) {
        const v = out[key]
        if (typeof v !== "string" || v.length < 6) continue
        let s = v
        for (const [a, b] of COPY_UPDATES) if (s.indexOf(a) !== -1) s = s.split(a).join(b)
        if (s !== v) {
            out[key] = s
            changed = true
        }
    }
    return changed ? out : props
}
